import XCTest
import GRDB
@testable import DVMFinanceKit

/// Parity tests against `Fixtures/rule_parity.json`, generated by
/// `Fixtures/generators/gen_rule_parity.py` from the real
/// `core/categorizer.py` implementation — see `ios/docs/plan.md` "Phase B".
///
/// `match_matrix` reconstructs the 23 rules the generator script defines
/// (`RULES` list) and asserts `Categorizer.applyRuleToTransaction` reproduces
/// the exact boolean matrix against the 4 fixture transactions.
/// `apply_rules_scenario` seeds an in-memory `AppDatabase` with the same 4
/// transactions + 5 rules the generator's `txn_rows`/`rules_rows` define, and
/// asserts `Categorizer.applyRules` reproduces the changes list and final DB
/// state exactly (order-insensitive on changes; compared by id).
final class CategorizerTests: XCTestCase {
    var appDatabase: AppDatabase!

    override func setUpWithError() throws {
        appDatabase = try AppDatabase.inMemory()
    }

    override func tearDownWithError() throws {
        appDatabase = nil
    }

    // MARK: - Fixture decoding

    private struct FixtureTransaction: Decodable {
        let description: String
        let descriptionStructured: String?
        let accountNumber: String
        let currency: String
        let transactiondate: String

        enum CodingKeys: String, CodingKey {
            case description
            case descriptionStructured = "description_structured"
            case accountNumber, currency, transactiondate
        }
    }

    private struct RuleMatchRow: Decodable {
        let rule: String
        let matches: [Bool]
    }

    private struct MatchMatrix: Decodable {
        let transactions: [FixtureTransaction]
        let rules: [RuleMatchRow]
    }

    private struct ChangeFixture: Decodable {
        let id: String
        let oldCategory: String?
        let newCategory: String?
        let oldTags: String?
        let newTags: String?

        enum CodingKeys: String, CodingKey {
            case id
            case oldCategory = "old_category"
            case newCategory = "new_category"
            case oldTags = "old_tags"
            case newTags = "new_tags"
        }
    }

    private struct FinalStateFixture: Decodable {
        let id: String
        let category: String?
        let manualCategory: String?
        let tags: String?
        let manualTags: String?
        let categorizationSource: String?

        enum CodingKeys: String, CodingKey {
            case id, category
            case manualCategory = "manual_category"
            case tags
            case manualTags = "manual_tags"
            case categorizationSource = "categorization_source"
        }
    }

    private struct ApplyRulesScenario: Decodable {
        let changes: [ChangeFixture]
        let final: [FinalStateFixture]
    }

    private struct RuleParityFixtures: Decodable {
        let matchMatrix: MatchMatrix
        let applyRulesScenario: ApplyRulesScenario

        enum CodingKeys: String, CodingKey {
            case matchMatrix = "match_matrix"
            case applyRulesScenario = "apply_rules_scenario"
        }
    }

    private func loadFixtures() throws -> RuleParityFixtures {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "rule_parity", withExtension: "json"))
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(RuleParityFixtures.self, from: data)
    }

    private static let dayFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(identifier: "UTC")
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter
    }()

    private func date(_ string: String) -> Date {
        Self.dayFormatter.date(from: string)!
    }

    private func decimal(_ string: String) -> Decimal {
        Decimal(string: string)!
    }

    // MARK: - Rule reconstruction (mirrors gen_rule_parity.py's RULES list)

    private func makeCondition(
        _ fieldTarget: String,
        _ matchPattern: String,
        _ matchValue: String,
        _ operatorValue: String = "AND",
        _ sortOrder: Int = 0
    ) -> RuleConditionRecord {
        RuleConditionRecord(
            ruleId: 0,
            fieldTarget: fieldTarget,
            matchPattern: matchPattern,
            matchValue: matchValue,
            operatorValue: operatorValue,
            sortOrder: sortOrder
        )
    }

    private func makeRule(
        _ name: String,
        ruleType: String = "full_description",
        matchPattern: String = "contains",
        fieldTarget: String? = "description",
        matchValue: String,
        conditions: [RuleConditionRecord] = [],
        filterAccount: String? = nil,
        filterCurrency: String? = nil,
        filterDateFrom: Date? = nil,
        filterDateTo: Date? = nil
    ) -> (String, Categorizer.RuleWithConditions) {
        let rule = CategorizationRuleRecord(
            ruleType: ruleType,
            matchPattern: matchPattern,
            fieldTarget: fieldTarget,
            matchValue: matchValue,
            filterAccount: filterAccount,
            filterCurrency: filterCurrency,
            filterDateFrom: filterDateFrom,
            filterDateTo: filterDateTo
        )
        return (name, Categorizer.RuleWithConditions(rule: rule, conditions: conditions))
    }

    private func buildAllRules() -> [(String, Categorizer.RuleWithConditions)] {
        [
            makeRule("contains_desc", matchValue: "albert heijn"),
            makeRule("exact_norm", matchPattern: "exact", matchValue: "WERO/Payment To John"),
            makeRule("starts_with", matchPattern: "starts_with", matchValue: "BEA, Betaalpas"),
            makeRule("ends_with", matchPattern: "ends_with", matchValue: "pas123"),
            makeRule("regex_ok", matchPattern: "regex", matchValue: #"albert\s*heijn"#),
            makeRule("regex_on_normalized", matchPattern: "regex", matchValue: "albert heijn"),
            makeRule("regex_invalid", matchPattern: "regex", matchValue: "(["),
            makeRule(
                "structured_field", ruleType: "structured_field", fieldTarget: "merchant",
                matchPattern: "exact", matchValue: "netflix"
            ),
            makeRule(
                "structured_bool", ruleType: "structured_field", fieldTarget: "recurring",
                matchPattern: "exact", matchValue: "true"
            ),
            makeRule(
                "structured_missing", ruleType: "structured_field", fieldTarget: "nope",
                matchPattern: "contains", matchValue: "x"
            ),
            makeRule(
                "iban_exact", ruleType: "account_iban", fieldTarget: "iban",
                matchPattern: "exact", matchValue: "NL91ABNA0417164300"
            ),
            makeRule(
                "iban_ends", ruleType: "account_iban", fieldTarget: "iban",
                matchPattern: "ends_with", matchValue: "4300"
            ),
            makeRule(
                "iban_from_desc_regex", ruleType: "account_iban", fieldTarget: "iban",
                matchPattern: "contains", matchValue: "ABNA"
            ),
            makeRule(
                "iban_desc_target", ruleType: "account_iban", fieldTarget: "description",
                matchPattern: "contains", matchValue: "overboeking"
            ),
            makeRule(
                "cond_and_true", matchValue: "netflix",
                conditions: [makeCondition("kind", "exact", "subscription")]
            ),
            makeRule(
                "cond_and_false", matchValue: "netflix",
                conditions: [makeCondition("kind", "exact", "movie")]
            ),
            makeRule(
                "cond_or_rescue", matchValue: "netflix",
                conditions: [
                    makeCondition("kind", "exact", "movie"),
                    makeCondition("merchant", "contains", "net", "OR", 1),
                ]
            ),
            makeRule("filter_account_match", matchValue: "albert", filterAccount: "NL91"),
            makeRule("filter_account_miss", matchValue: "albert", filterAccount: "NL02"),
            makeRule("filter_currency", matchValue: "payment", filterCurrency: "USD"),
            makeRule(
                "filter_date_window", matchValue: "albert",
                filterDateFrom: date("2026-01-01"), filterDateTo: date("2026-01-31")
            ),
            makeRule("filter_date_excludes", matchValue: "netflix", filterDateTo: date("2026-02-28")),
            makeRule("no_structured_no_field", fieldTarget: "merchant", matchValue: "netflix"),
        ]
    }

    // MARK: - match_matrix

    func testMatchMatrixParity() throws {
        let fixtures = try loadFixtures()

        let contexts = fixtures.matchMatrix.transactions.map { txn in
            Categorizer.MatchContext(
                description: txn.description,
                descriptionStructured: txn.descriptionStructured,
                accountNumber: txn.accountNumber,
                currency: txn.currency,
                transactiondate: date(txn.transactiondate)
            )
        }
        XCTAssertEqual(contexts.count, 4)

        var rulesByName: [String: Categorizer.RuleWithConditions] = [:]
        for (name, rule) in buildAllRules() {
            rulesByName[name] = rule
        }
        XCTAssertEqual(rulesByName.count, 23, "must reconstruct all 23 rules from gen_rule_parity.py")

        for row in fixtures.matchMatrix.rules {
            guard let entry = rulesByName[row.rule] else {
                XCTFail("no reconstructed rule named \(row.rule)")
                continue
            }
            XCTAssertEqual(row.matches.count, contexts.count)
            for (index, context) in contexts.enumerated() {
                let actual = Categorizer.applyRuleToTransaction(
                    rule: entry.rule,
                    conditions: entry.conditions,
                    context: context
                )
                XCTAssertEqual(actual, row.matches[index], "rule=\(row.rule) txn=\(index)")
            }
        }
    }

    // MARK: - apply_rules_scenario

    func testApplyRulesScenarioParity() throws {
        let fixtures = try loadFixtures()

        let txn1 = TransactionRecord(
            id: "t1", accountNumber: "NL91", transactiondate: date("2026-01-15"),
            amount: decimal("-12.30"), description: "BEA, Betaalpas Albert Heijn 1234,PAS123",
            currency: "EUR"
        )
        let txn2 = TransactionRecord(
            id: "t2", accountNumber: "NL91", transactiondate: date("2026-02-01"),
            amount: decimal("-50"), description: "Netflix subscription", currency: "EUR"
        )
        let txn3 = TransactionRecord(
            id: "t3", accountNumber: "NL91", transactiondate: date("2026-02-02"),
            amount: decimal("-5"), description: "Netflix subscription extra",
            category: "old-cat", manualCategory: "entertainment-manual",
            tags: "old-tag", manualTags: "keep", categorizationSource: "manual", currency: "EUR"
        )
        let txn4 = TransactionRecord(
            id: "t4", accountNumber: "NL91", transactiondate: date("2026-02-03"),
            amount: decimal("-9"), description: "nothing matches me",
            category: "stale", tags: "staletag", categorizationSource: "99", currency: "EUR"
        )

        var rule1 = CategorizationRuleRecord(
            id: 1, uuid: "u1", priority: 10, ruleType: "full_description", matchPattern: "contains",
            fieldTarget: "description", matchValue: "albert heijn", category: "Groceries-AH", tags: "food",
            isActive: true, isTagOnly: false
        )
        var rule2 = CategorizationRuleRecord(
            id: 2, uuid: "u2", priority: 20, ruleType: "full_description", matchPattern: "contains",
            fieldTarget: "description", matchValue: "netflix", category: "entertainment", tags: nil,
            isActive: true, isTagOnly: false
        )
        var rule3 = CategorizationRuleRecord(
            id: 3, uuid: "u3", priority: 5, ruleType: "full_description", matchPattern: "contains",
            fieldTarget: "description", matchValue: "netflix", category: "should-not-win-inactive",
            isActive: false, isTagOnly: false
        )
        var rule4 = CategorizationRuleRecord(
            id: 4, uuid: "u4", priority: 100, ruleType: "full_description", matchPattern: "contains",
            fieldTarget: "description", matchValue: "subscription", category: nil, tags: "recurring,large",
            isActive: true, isTagOnly: true
        )
        var rule5 = CategorizationRuleRecord(
            id: 5, uuid: "u5", priority: 100, ruleType: "full_description", matchPattern: "contains",
            fieldTarget: "description", matchValue: "netflix", category: nil, tags: "recurring,video",
            isActive: true, isTagOnly: true
        )

        try appDatabase.dbWriter.write { db in
            try txn1.insert(db)
            try txn2.insert(db)
            try txn3.insert(db)
            try txn4.insert(db)
            try rule1.insert(db)
            try rule2.insert(db)
            try rule3.insert(db)
            try rule4.insert(db)
            try rule5.insert(db)
        }

        let changes = try appDatabase.dbWriter.write { db in
            try Categorizer.applyRules(db: db)
        }

        var changesByID: [String: Categorizer.TxnChange] = [:]
        for change in changes {
            changesByID[change.transactionId] = change
        }
        XCTAssertEqual(
            changesByID.count, fixtures.applyRulesScenario.changes.count,
            "change count must match exactly (order-insensitive, compared by id)"
        )

        for expected in fixtures.applyRulesScenario.changes {
            let actual = try XCTUnwrap(changesByID[expected.id], "missing change for \(expected.id)")
            XCTAssertEqual(actual.oldCategory, expected.oldCategory, "\(expected.id) oldCategory")
            XCTAssertEqual(actual.newCategory, expected.newCategory, "\(expected.id) newCategory")
            XCTAssertEqual(actual.oldTags, expected.oldTags, "\(expected.id) oldTags")
            XCTAssertEqual(actual.newTags, expected.newTags, "\(expected.id) newTags")
        }

        let finalRecords = try appDatabase.dbWriter.read { db in
            try TransactionRecord.fetchAll(db)
        }
        var finalByID: [String: TransactionRecord] = [:]
        for record in finalRecords {
            finalByID[record.id] = record
        }
        XCTAssertEqual(finalByID.count, fixtures.applyRulesScenario.final.count)

        for expected in fixtures.applyRulesScenario.final {
            let actual = try XCTUnwrap(finalByID[expected.id], "missing final state for \(expected.id)")
            XCTAssertEqual(actual.category, expected.category, "\(expected.id) category")
            XCTAssertEqual(actual.manualCategory, expected.manualCategory, "\(expected.id) manualCategory")
            XCTAssertEqual(actual.tags, expected.tags, "\(expected.id) tags")
            XCTAssertEqual(actual.manualTags, expected.manualTags, "\(expected.id) manualTags")
            XCTAssertEqual(
                actual.categorizationSource, expected.categorizationSource,
                "\(expected.id) categorizationSource"
            )
        }
    }

    // MARK: - recordRuleChange / ruleSnapshot (not fixture-covered, direct assertions)

    func testRecordRuleChangePersistsReportAndItems() throws {
        let txn = TransactionRecord(
            id: "r1", accountNumber: "NL91", transactiondate: date("2026-01-15"),
            amount: decimal("-12.30"), description: "Albert Heijn groceries", currency: "EUR"
        )
        var rule = CategorizationRuleRecord(
            uuid: "rule-uuid-1", priority: 10, ruleType: "full_description", matchPattern: "contains",
            fieldTarget: "description", matchValue: "albert heijn", category: "Groceries", tags: "food"
        )

        try appDatabase.dbWriter.write { db in
            try txn.insert(db)
            try rule.insert(db)
        }

        let ruleId = try XCTUnwrap(rule.id)
        let afterSnapshot = Categorizer.ruleSnapshot(rule: rule, conditions: [])
        XCTAssertNotNil(afterSnapshot)
        XCTAssertTrue(afterSnapshot!.contains("\"uuid\":\"rule-uuid-1\""))

        let report = try appDatabase.dbWriter.write { db in
            try Categorizer.recordRuleChange(
                db: db, action: "import", before: nil, after: afterSnapshot,
                ruleId: ruleId, ruleUuid: "rule-uuid-1"
            )
        }

        XCTAssertEqual(report.action, "import")
        XCTAssertEqual(report.ruleId, ruleId)
        XCTAssertEqual(report.ruleUuid, "rule-uuid-1")
        XCTAssertEqual(report.summaryDictionary?["changed"] as? Int, 1)

        let items = try appDatabase.dbWriter.read { db in
            try RuleChangeItemRecord.filter(Column("report_id") == report.id!).fetchAll(db)
        }
        XCTAssertEqual(items.count, 1)
        XCTAssertEqual(items.first?.transactionId, "r1")
        XCTAssertEqual(items.first?.newCategory, "groceries")
        XCTAssertEqual(items.first?.newTags, "food")

        let updatedTxn = try appDatabase.dbWriter.read { db in
            try TransactionRecord.fetchOne(db, key: "r1")
        }
        XCTAssertEqual(updatedTxn?.category, "groceries")
        XCTAssertEqual(updatedTxn?.categorizationSource, String(ruleId))
    }

    func testRuleSnapshotNilRuleReturnsNil() {
        XCTAssertNil(Categorizer.ruleSnapshot(rule: nil, conditions: []))
    }
}
