import XCTest
@testable import DVMFinanceKit

/// Parity tests against `Fixtures/parity.json`, generated by
/// `Fixtures/generators/gen_parity_fixtures.py` from the real
/// `core/utils.py` implementation — see `ios/docs/plan.md` "Phase B".
final class NormalizeTests: XCTestCase {

    private struct StringCase: Decodable {
        let input: String?
        let expected: String
    }

    private struct CategoryCase: Decodable {
        let input: String?
        let expected: String?
    }

    private struct HashCase: Decodable {
        let date: String?
        let description: String?
        let amount: String?
        let account: String?
        let expected: String
    }

    private struct ParityFixtures: Decodable {
        let normalizeStringForMatching: [StringCase]
        let normalizeCategory: [CategoryCase]
        let transactionHash: [HashCase]

        enum CodingKeys: String, CodingKey {
            case normalizeStringForMatching = "normalize_string_for_matching"
            case normalizeCategory = "normalize_category"
            case transactionHash = "transaction_hash"
        }
    }

    private func loadFixtures() throws -> ParityFixtures {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "parity", withExtension: "json"))
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(ParityFixtures.self, from: data)
    }

    private static let dayFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(identifier: "UTC")
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter
    }()

    func testNormalizeStringForMatchingParity() throws {
        let fixtures = try loadFixtures()
        for testCase in fixtures.normalizeStringForMatching {
            XCTAssertEqual(
                CoreNormalize.normalizeStringForMatching(testCase.input),
                testCase.expected,
                "input: \(String(describing: testCase.input))"
            )
        }
    }

    func testUmlautCaseIsCovered() throws {
        let fixtures = try loadFixtures()
        XCTAssertTrue(
            fixtures.normalizeStringForMatching.contains { $0.input == "Ümlaut Ströße" },
            "parity.json must include the Ümlaut Ströße case per CLAUDE.md"
        )
        XCTAssertEqual(CoreNormalize.normalizeStringForMatching("Ümlaut Ströße"), "ümlautströße")
    }

    func testNormalizeCategoryParity() throws {
        let fixtures = try loadFixtures()
        for testCase in fixtures.normalizeCategory {
            XCTAssertEqual(
                CoreNormalize.normalizeCategory(testCase.input),
                testCase.expected,
                "input: \(String(describing: testCase.input))"
            )
        }
    }

    func testTransactionHashParity() throws {
        let fixtures = try loadFixtures()
        for testCase in fixtures.transactionHash {
            let date = testCase.date.flatMap { Self.dayFormatter.date(from: $0) }
            let amount = CoreNormalize.HashAmountInput(testCase.amount)
            let actual = CoreNormalize.calculateTransactionHash(
                date: date,
                description: testCase.description,
                amount: amount,
                account: testCase.account
            )
            let message = "date=\(testCase.date ?? "nil") description=\(testCase.description ?? "nil") "
                + "amount=\(testCase.amount ?? "nil") account=\(testCase.account ?? "nil")"
            XCTAssertEqual(actual, testCase.expected, message)
        }
    }

    func testCategorySeparator() {
        XCTAssertEqual(CoreNormalize.categorySeparator, "-")
    }

    func testIsTransferCategoryPrefix() {
        XCTAssertTrue(CoreNormalize.isTransferCategory("Transfer-Wise"))
        XCTAssertTrue(CoreNormalize.isTransferCategory("transfer"))
        XCTAssertFalse(CoreNormalize.isTransferCategory("groceries-transfer"), "must be a prefix match, not substring")
        XCTAssertFalse(CoreNormalize.isTransferCategory(nil))
        XCTAssertFalse(CoreNormalize.isTransferCategory(""))
    }
}
