import XCTest
@testable import DVMFinanceKit

/// Parity tests against `Fixtures/parity.json`'s `transaction_id` and
/// `transaction_id_float_amounts` keys — see
/// `Fixtures/generators/gen_parity_fixtures.py` and `ios/docs/spec.md`
/// "Transaction identity & dedup".
final class TransactionIDTests: XCTestCase {

    /// Mirrors one entry of `parity.json`'s `transaction_id` array. These
    /// cases were generated by feeding `Decimal`/`date` values directly into
    /// Python's `generate_transaction_id`, so `amount`/`transactiondate` are
    /// serialized as the exact `str(Decimal(...))`/`str(date(...))` strings
    /// (preserving trailing zeros a `Double` cannot, e.g. `"100.00"` /
    /// `"100"`) — every field decodes as `String?` here (missing key and
    /// JSON `null` both decode to `nil`, which is the correct behavior for
    /// this test: both mean "render as Python's `str(None)` == \"None\"").
    private struct IDCase: Decodable {
        let accountNumber: String
        let transactiondate: String?
        let amount: String?
        let description: String?
        let paypalTransactionId: String?
        let wiseTransactionId: String?
        let sebVoucherId: String?
        let expected: String

        enum CodingKeys: String, CodingKey {
            case accountNumber
            case transactiondate
            case amount
            case description
            case paypalTransactionId = "paypal_transaction_id"
            case wiseTransactionId = "wise_transaction_id"
            case sebVoucherId = "seb_voucher_id"
            case expected
        }
    }

    private struct FloatAmountCase: Decodable {
        let accountNumber: String
        let transactiondate: String
        let amount: Double
        let description: String
        let amountStrPython: String
        let expected: String

        enum CodingKeys: String, CodingKey {
            case accountNumber, transactiondate, amount, description
            case amountStrPython = "amount_str_python"
            case expected
        }
    }

    private struct ParityFixtures: Decodable {
        let transactionId: [IDCase]
        let transactionIdFloatAmounts: [FloatAmountCase]

        enum CodingKeys: String, CodingKey {
            case transactionId = "transaction_id"
            case transactionIdFloatAmounts = "transaction_id_float_amounts"
        }
    }

    private func loadFixtures() throws -> ParityFixtures {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "parity", withExtension: "json"))
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(ParityFixtures.self, from: data)
    }

    private static let dayFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(identifier: "UTC")
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter
    }()

    /// Exercises the low-level, string-component API directly — the only
    /// way to reproduce fixture cases that embed a Python `Decimal`
    /// rendering (e.g. `"100.00"`, `"100"`) byte-for-byte, since the
    /// production `Double`-based `ParsedTransaction` API cannot recreate a
    /// trailing zero a `Double` doesn't retain. `nil` fixture fields (missing
    /// key or JSON `null` — both mean the same thing here, see `IDCase`'s doc
    /// comment) render as the literal `"None"`, matching Python's
    /// `str(trans.get(key, ""))` when the dict *has* the key with value
    /// `None`.
    func testTransactionIDParity() throws {
        let fixtures = try loadFixtures()
        for testCase in fixtures.transactionId {
            let actual = TransactionID.generateTransactionID(
                account: testCase.accountNumber,
                paypalTransactionId: testCase.paypalTransactionId,
                wiseTransactionId: testCase.wiseTransactionId,
                sebVoucherId: testCase.sebVoucherId,
                dateComponent: testCase.transactiondate ?? "None",
                amountComponent: testCase.amount ?? "None",
                descriptionComponent: testCase.description ?? "None"
            )
            XCTAssertEqual(actual, testCase.expected, "accountNumber=\(testCase.accountNumber)")
        }
    }

    /// The final `transaction_id` fixture case has every optional field
    /// `null` (account is `""`, not `None`) — explicitly asserted here
    /// because it is the surprising "`None`-as-literal-string" case flagged
    /// in `CLAUDE.md`.
    func testAllNilCaseRendersLiteralNone() throws {
        let fixtures = try loadFixtures()
        let lastCase = try XCTUnwrap(fixtures.transactionId.last)
        XCTAssertEqual(lastCase.accountNumber, "")
        XCTAssertNil(lastCase.transactiondate)
        XCTAssertNil(lastCase.amount)
        XCTAssertNil(lastCase.description)
        XCTAssertEqual(lastCase.expected, "_None_None_6adf97f83acf6453")

        let transaction = ParsedTransaction(accountNumber: "")
        XCTAssertEqual(TransactionID.generateTransactionID(transaction), lastCase.expected)
    }

    /// Exercises the production `ParsedTransaction` (`Double` amount, `Date`
    /// transaction date) API — the shape Phase D parsers will actually
    /// produce — against the `transaction_id_float_amounts` fixture, which
    /// exists specifically to guard the `Double` `str(float)` rendering (see
    /// `ios/docs/plan.md` "Phase B" and `ios/docs/spec.md` "Transaction
    /// identity & dedup").
    func testTransactionIDFloatAmountsParity() throws {
        let fixtures = try loadFixtures()
        for testCase in fixtures.transactionIdFloatAmounts {
            // Guard the amount-rendering fidelity itself: Swift's default
            // Double string interpolation must match Python's str(float).
            XCTAssertEqual("\(testCase.amount)", testCase.amountStrPython)

            let date = try XCTUnwrap(Self.dayFormatter.date(from: testCase.transactiondate))
            let transaction = ParsedTransaction(
                accountNumber: testCase.accountNumber,
                transactiondate: date,
                amount: testCase.amount,
                description: testCase.description
            )
            XCTAssertEqual(TransactionID.generateTransactionID(transaction), testCase.expected)
        }
    }

    func testPaypalWiseSebPriorityOrder() {
        // account_paypal_transaction_id wins over wise/seb when all three are present.
        let transaction = ParsedTransaction(
            accountNumber: "acct",
            transactiondate: Self.dayFormatter.date(from: "2026-01-01"),
            amount: 1.0,
            description: "d",
            paypalTransactionId: "PP1",
            wiseTransactionId: "W1",
            sebVoucherId: "S1"
        )
        XCTAssertEqual(TransactionID.generateTransactionID(transaction), "acct_PP1")

        let wiseOnly = ParsedTransaction(
            accountNumber: "acct",
            paypalTransactionId: nil,
            wiseTransactionId: "W1",
            sebVoucherId: "S1"
        )
        XCTAssertEqual(TransactionID.generateTransactionID(wiseOnly), "acct_W1")

        let sebOnly = ParsedTransaction(accountNumber: "acct", sebVoucherId: "S1")
        XCTAssertEqual(TransactionID.generateTransactionID(sebOnly), "acct_S1")
    }
}
