"""initial schema

Revision ID: 10222b47646b
Revises: 
Create Date: 2026-07-07 03:16:39.912774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10222b47646b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('idx_budgets_category', ['category'], unique=False)
        batch_op.create_index('idx_budgets_category_period', ['category', 'period'], unique=True)
        batch_op.create_index('idx_budgets_period', ['period'], unique=False)

    op.create_table('categorization_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('match_pattern', sa.String(length=50), nullable=False),
    sa.Column('field_target', sa.String(length=50), nullable=True),
    sa.Column('match_value', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('filter_account', sa.String(), nullable=True),
    sa.Column('filter_currency', sa.String(length=3), nullable=True),
    sa.Column('filter_date_from', sa.Date(), nullable=True),
    sa.Column('filter_date_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.create_index('idx_rules_priority_active', ['priority', 'is_active'], unique=False)
        batch_op.create_index('idx_rules_type', ['rule_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_categorization_rules_uuid'), ['uuid'], unique=True)

    op.create_table('download_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_range_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_state', schema=None) as batch_op:
        batch_op.create_index('idx_download_state_source_account', ['source', 'account'], unique=True)
        batch_op.create_index(batch_op.f('ix_download_state_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_state_source'), ['source'], unique=False)

    op.create_table('rule_change_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_uuid', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('rule_before', sa.JSON(), nullable=True),
    sa.Column('rule_after', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_change_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_change_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_change_reports_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_change_reports_rule_uuid'), ['rule_uuid'], unique=False)

    op.create_table('snapshot_imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_machine_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=True),
    sa.Column('overwrites', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshot_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_imports_created_at'), ['created_at'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('accountNumber', sa.String(), nullable=False),
    sa.Column('mutationcode', sa.String(), nullable=True),
    sa.Column('transactiondate', sa.Date(), nullable=False),
    sa.Column('valuedate', sa.Date(), nullable=True),
    sa.Column('startsaldo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('endsaldo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('description_structured', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('manual_category', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('manual_tags', sa.String(), nullable=True),
    sa.Column('categorization_source', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('transaction_type_code', sa.String(), nullable=True),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_account_date', ['accountNumber', 'transactiondate'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_accountNumber'), ['accountNumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_manual_category'), ['manual_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_hash'), ['transaction_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transactiondate'), ['transactiondate'], unique=False)

    op.create_table('rule_change_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('old_category', sa.String(), nullable=True),
    sa.Column('new_category', sa.String(), nullable=True),
    sa.Column('old_tags', sa.String(), nullable=True),
    sa.Column('new_tags', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['rule_change_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_change_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_change_items_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_change_items_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('field_target', sa.String(length=50), nullable=False),
    sa.Column('match_pattern', sa.String(length=50), nullable=False),
    sa.Column('match_value', sa.String(length=500), nullable=False),
    sa.Column('operator', sa.String(length=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['categorization_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_conditions_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_conditions_rule_id'))

    op.drop_table('rule_conditions')
    with op.batch_alter_table('rule_change_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_change_items_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_rule_change_items_report_id'))

    op.drop_table('rule_change_items')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transactiondate'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_hash'))
        batch_op.drop_index(batch_op.f('ix_transactions_manual_category'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))
        batch_op.drop_index(batch_op.f('ix_transactions_amount'))
        batch_op.drop_index(batch_op.f('ix_transactions_accountNumber'))
        batch_op.drop_index('idx_account_date')

    op.drop_table('transactions')
    with op.batch_alter_table('snapshot_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_imports_created_at'))

    op.drop_table('snapshot_imports')
    with op.batch_alter_table('rule_change_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_change_reports_rule_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_change_reports_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_change_reports_created_at'))

    op.drop_table('rule_change_reports')
    with op.batch_alter_table('download_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_state_source'))
        batch_op.drop_index(batch_op.f('ix_download_state_account'))
        batch_op.drop_index('idx_download_state_source_account')

    op.drop_table('download_state')
    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorization_rules_uuid'))
        batch_op.drop_index('idx_rules_type')
        batch_op.drop_index('idx_rules_priority_active')

    op.drop_table('categorization_rules')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('idx_budgets_period')
        batch_op.drop_index('idx_budgets_category_period')
        batch_op.drop_index('idx_budgets_category')

    op.drop_table('budgets')
    # ### end Alembic commands ###
