"""add updated_at, export_state, snapshot delta provenance

Revision ID: 7dd060546159
Revises: d42e198530e9
Create Date: 2026-07-16 16:49:01.561320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd060546159'
down_revision: Union[str, None] = 'd42e198530e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_delta_export_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshot_imports', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_delta', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('delta_since', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_updated_at'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('snapshot_imports', schema=None) as batch_op:
        batch_op.drop_column('delta_since')
        batch_op.drop_column('is_delta')

    op.drop_table('export_state')
    # ### end Alembic commands ###
