"""Add is_tag_only field to CategorizationRule

Revision ID: d42e198530e9
Revises: 10222b47646b
Create Date: 2026-07-11 21:46:00.176703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42e198530e9'
down_revision: Union[str, None] = '10222b47646b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_tag_only', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('is_tag_only')

    # ### end Alembic commands ###
